version: "3.5"

services:
  postgres-db:
    image: postgres:16-alpine
    hostname: postgres-db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql

  order-api:
    build: .
    image: gui9394/order-api:latest
    hostname: order-api
    environment:
      - SERVER_PORT=8080
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=postgres-db:5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - ORDER_CONSULT_FIND_BY_DATE_INTERVAL_MAX=30
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
