logging:
  pattern:
    console: "%d{ISO8601} type=%highlight(%level) thread=%magenta(%thread) traceId=%magenta(%mdc{traceId}) spanId=%magenta(%mdc{spanId}) class=%cyan(%class{0}) method=%green(%method) line=%yellow(%line) %m%n%xThrowable"

  level:
    org.springframework.batch: error

server:
  error:
    include-message: always

spring:
  application:
    name: order

  batch:
    job:
      enabled: false
    initialize-schema: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:rinha}?escapeSyntaxCallMode=callIfNoReturn
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:123}

order:
  consult:
    find-by-date-interval-max: 15

  process:
    chunk-size: 10000
